name: lingo-dev

services:
  postgres:
    image: postgres
    container_name: lingo-dev-postgres
    environment:
      POSTGRES_DB: lingo-dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - lingo-dev_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  lingo-dev_postgres_data:
